#!/usr/bin/env python3
"""Export the stored corpus as a Markdown vault, one folder per project.

The database is the archive; Markdown is how you read it five years from
now without this tool installed. Each project becomes a folder, each
folder holds its sessions in one chronological file (oldest first), and
each session reproduces what actually happened: the prompt, the answer,
every tool the assistant reached for, the commands it ran, and a link to
every file it created or changed.

Layout::

    <out>/
      README.md                     index of projects, most recent first
      <Project>/
        <Project>.md                all sessions, oldest first
        <Project> 2026-08-04.md     dated parts once the file grows large
        Memory.md                   extracted memory chunks for the project

Machine-generated conversations (``generated_by IS NOT NULL`` — the
tool's own ``claude -p`` calls) are excluded by default: they hold no
human prompt, and including them buries the sessions you actually had.
``--include-generated`` puts them back.

Usage::

    throughline export-markdown --out ~/Obsidian/Throughline
    throughline export-markdown --out DIR --project throughline
    throughline export-markdown --out DIR --since 2026-01-01
    throughline export-markdown --out DIR --tool-output 400
    throughline export-markdown --out DIR --redact

Exit code: 0 on success, 1 on DB failure, 2 on a usage error.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import defaultdict
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

import psycopg2
import psycopg2.extras

from throughline import pii

# --------------------------------------------------------------------------- #
# Tuning                                                                      #
# --------------------------------------------------------------------------- #

#: Split a project file into dated parts once it passes this many bytes.
#: Obsidian's editor becomes visibly sluggish somewhere above a megabyte;
#: this keeps every part comfortably below that.
DEFAULT_SPLIT_BYTES = 1_500_000

#: Cap on a single message's rendered text. Long transcripts are the norm,
#: but a single 200 kB paste helps nobody read the session.
MAX_MESSAGE_CHARS = 12_000

#: Cap on a rendered shell command.
MAX_COMMAND_CHARS = 4_000

#: Tool inputs that name a file the assistant touched.
_PATH_KEYS = ("file_path", "path", "notebook_path", "filePath")

#: Tools whose use means the file changed, not merely that it was read.
_WRITE_TOOLS = {"edit", "write", "notebookedit", "multiedit", "write_file", "str_replace_editor", "apply_patch"}

#: User-message prefixes that are harness injections, not something the
#: person typed. Dropping them is the difference between a readable
#: transcript and a wall of skill boilerplate.
_INJECTED_PREFIXES = (
    "<system-reminder>",
    "<local-command-",
    "<command-name>",
    "<command-message>",
    "Base directory for this skill:",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running local commands",
)

#: How the person is labelled in the transcript. A published tool must not
#: carry one person's name in its output, so this is a default with an
#: override rather than a constant.
AUTHOR_ENV = "THROUGHLINE_AUTHOR"
DEFAULT_AUTHOR = "You"


def author() -> str:
    """What to call the person whose prompts these are."""
    return os.environ.get(AUTHOR_ENV, "").strip() or DEFAULT_AUTHOR


_SLUG_STRIP = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def db_config() -> dict[str, Any]:
    return {
        "host": os.environ.get("PGHOST", "localhost"),
        "port": int(os.environ.get("PGPORT", "5432")),
        "dbname": os.environ.get("PGDATABASE", "throughline"),
        "user": os.environ.get("PGUSER", os.environ.get("USER", "postgres")),
        **({"password": os.environ["PGPASSWORD"]} if os.environ.get("PGPASSWORD") else {}),
    }


# --------------------------------------------------------------------------- #
# Formatting helpers                                                          #
# --------------------------------------------------------------------------- #


def safe_name(value: str | None) -> str:
    """Turn a project name into something every filesystem accepts."""
    name = (value or "unknown").strip() or "unknown"
    name = _SLUG_STRIP.sub("-", name)
    name = name.strip(". ")
    return name or "unknown"


def file_url(path: str) -> str:
    """Absolute ``file://`` URL for a path, percent-escaping what matters.

    Obsidian follows these, so a link in the export opens the real file
    even though the file lives outside the vault.
    """
    from urllib.parse import quote

    return "file://" + quote(path, safe="/:")


def resolve_path(raw: str, project_path: str | None) -> str:
    """Make a tool's file argument absolute, using the session's cwd."""
    p = Path(raw).expanduser()
    if p.is_absolute():
        return str(p)
    if project_path:
        return str(Path(project_path).expanduser() / p)
    return str(p)


def link(raw: str, project_path: str | None, *, redact: bool = False) -> str:
    """Markdown link to a file, labelled by its path within the project.

    A bare basename is ambiguous the moment two ``index.html`` files show
    up in one session, so the label keeps whatever part of the path sits
    below the project root.

    Not every session knows where it ran: some adapters record a bare
    project name as ``project_path``, which leaves a relative tool
    argument unresolvable. A ``file://`` URL built from one of those
    points nowhere, so those render as plain code instead — an honest
    path beats a link that fails silently.
    """
    resolved = resolve_path(raw, project_path)
    if redact:
        # Redaction rewrites the home directory out of the path, which makes
        # any URL built from it point nowhere. Show the safe path instead of
        # a link that cannot resolve.
        return f"`{pii.redact(resolved)}`"
    if not Path(resolved).is_absolute():
        return f"`{resolved}`"

    label = Path(resolved).name
    if project_path:
        try:
            label = str(Path(resolved).relative_to(Path(project_path).expanduser()))
        except ValueError:
            pass
    return f"[{label}]({file_url(resolved)})"


_HEADING = re.compile(r"^(#{1,6})(\s)")
_FENCE = re.compile(r"^\s*(```|~~~)")


def demote_headings(text: str) -> str:
    """Push any heading inside a message below the ones the export owns.

    The export uses ``##`` for a session and ``###`` for a turn. A message
    that quotes a Markdown heading — a report the assistant wrote, a README
    it pasted — would otherwise forge a session boundary: on one corpus 22
    such lines appeared in the outline as sessions that never happened, and
    four of them looked like the chronology had broken.

    Fenced blocks are left alone. A shell comment starts with ``#`` at the
    beginning of a line too, and demoting it would corrupt the command.
    """
    out: list[str] = []
    fenced = False
    for line in text.split("\n"):
        if _FENCE.match(line):
            fenced = not fenced
            out.append(line)
            continue
        if not fenced:
            match = _HEADING.match(line)
            if match:
                level = min(len(match.group(1)) + 3, 6)
                out.append("#" * level + line[match.end(1) :])
                continue
        out.append(line)
    return "\n".join(out)


def _clean(text: str, redact: bool) -> str:
    """Run *text* through the PII pass when the export asked for it.

    The same heuristic pass that guards the extraction pipeline: API-key
    shapes, JWTs, bearer headers, ``password=`` assignments, private-key
    blocks, email addresses, and home-directory usernames. It is
    conservative — it will not catch an unusual secret shape — so it
    reduces exposure rather than guaranteeing there is none.
    """
    return pii.redact(text) if redact else text


def prose(text: str, redact: bool, limit: int = MAX_MESSAGE_CHARS) -> str:
    """Prepare a message body for the document it is about to land in.

    Redact if asked, demote any heading so the message cannot forge a
    session boundary, truncate, and then close a code fence the truncation
    cut in half — an unbalanced fence swallows the rest of the file into a
    code block, so the damage is not local to the message.
    """
    body = truncate(demote_headings(_clean(text, redact)), limit)
    if len([line for line in body.split("\n") if _FENCE.match(line)]) % 2:
        body += "\n```"
    return body


def truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + f"\n\n*… {len(text) - limit:,} more characters omitted*"


def block_text(row: dict[str, Any]) -> str:
    """Best available text for a message.

    ``content`` is the flattened text for most adapters; where it is empty
    the text still lives in ``content_blocks``. Thinking blocks are left
    out — they are the assistant's scratchpad, not what it said.

    Ingestion also flattens each tool_use block into ``content`` as a
    ``[Tool: Name]`` stanza followed by its raw arguments. That is the
    same call this exporter renders from ``tool_calls``, so treating it as
    prose would print every command twice — once as JSON, once properly.
    """
    content = (row.get("content") or "").strip()
    if content and not content.startswith("[Tool:"):
        return content
    blocks = row.get("content_blocks")
    if isinstance(blocks, list):
        parts = [str(b.get("text", "")).strip() for b in blocks if isinstance(b, dict) and b.get("type") == "text"]
        joined = "\n\n".join(p for p in parts if p)
        if joined:
            return joined
    return "" if content.startswith("[Tool:") else content


def is_injected(text: str) -> bool:
    stripped = text.lstrip()
    return any(stripped.startswith(prefix) for prefix in _INJECTED_PREFIXES)


#: Models the adapters record that are not a model anyone chose.
_PLACEHOLDER_MODELS = {"<synthetic>", "unknown", ""}


def speaker(conv: dict[str, Any], msg: dict[str, Any]) -> str:
    """Which assistant produced this turn.

    Named per turn rather than per session: a long session routes work to
    whatever model fits — on one corpus a single tool answered from nine
    different models — so the session header cannot say which one wrote a
    given paragraph. Falls back to the session's model when a message does
    not carry its own.
    """
    tool = (conv.get("source_tool") or "").strip()
    model = (msg.get("model") or conv.get("model") or "").strip()
    if model in _PLACEHOLDER_MODELS:
        model = ""
    parts = [p for p in (tool, model) if p]
    return " · ".join(parts) if parts else "KI"


def render_tool_call(call: dict[str, Any], project_path: str | None, *, redact: bool = False) -> tuple[str, str | None]:
    """Render one tool call. Returns (markdown, changed_file_or_None)."""
    name = str(call.get("tool_name") or call.get("name") or "tool")
    payload = call.get("input")
    if not isinstance(payload, dict):
        return f"**{name}**", None

    lower = name.lower()
    note = str(payload.get("description") or "").strip()

    # A shell command is the most legible thing we can show.
    command = payload.get("command")
    if isinstance(command, str) and command.strip():
        head = f"**{name}**" + (f" — {note}" if note else "")
        body = truncate(_clean(command.strip(), redact), MAX_COMMAND_CHARS)
        return f"{head}\n\n```bash\n{body}\n```", None

    # A file argument: link it, and remember it if the file was written.
    for key in _PATH_KEYS:
        raw = payload.get(key)
        if isinstance(raw, str) and raw.strip():
            touched = resolve_path(raw.strip(), project_path) if lower in _WRITE_TOOLS else None
            verb = "writes" if lower in _WRITE_TOOLS else "reads"
            return f"**{name}** {verb} {link(raw.strip(), project_path, redact=redact)}", touched

    # Everything else: a one-line summary of the arguments.
    for key in ("prompt", "query", "pattern", "url", "skill", "message", "subject"):
        raw = payload.get(key)
        if isinstance(raw, str) and raw.strip():
            return f"**{name}** · {prose(raw.strip(), redact, 300)}", None

    compact = _clean(json.dumps(payload, ensure_ascii=False), redact)[:300]
    return f"**{name}** · `{compact}`", None


def render_session(
    conv: dict[str, Any], messages: list[dict[str, Any]], tool_output: int, *, redact: bool = False
) -> str:
    """Render one conversation as a Markdown section."""
    project_path = conv.get("project_path")
    started = conv["started_at"]
    title = (conv.get("summary") or "").strip().splitlines()[0] if conv.get("summary") else ""
    title = _clean(title, redact)[:120] or "Session"

    body: list[str] = []
    touched: list[str] = []
    seen: set[str] = set()

    for msg in messages:
        stamp = msg["created_at"].strftime("%H:%M")
        role = msg["role"]
        text = block_text(msg)

        if role == "user":
            if not text or is_injected(text):
                continue
            body.append(f"### {stamp} · Prompt · {author()}\n\n{prose(text, redact)}")
            continue

        if role == "tool_result":
            if tool_output <= 0 or not text:
                continue
            body.append(
                f"<details><summary>{stamp} · Output</summary>\n\n"
                f"```\n{truncate(_clean(text, redact), tool_output)}\n```\n\n</details>"
            )
            continue

        # assistant — what it said and what it did are separate turns, each
        # naming the model that produced it.
        who = speaker(conv, msg)
        chunk: list[str] = []
        if text:
            chunk.append(f"### {stamp} · Answer · {who}\n\n{prose(text, redact)}")

        actions: list[str] = []
        calls = msg.get("tool_calls")
        if isinstance(calls, list):
            for call in calls:
                if not isinstance(call, dict):
                    continue
                rendered, changed = render_tool_call(call, project_path, redact=redact)
                actions.append(rendered)
                if changed and changed not in seen:
                    seen.add(changed)
                    touched.append(changed)
        if actions:
            chunk.append(f"### {stamp} · Execution · {who}\n\n" + "\n\n".join(actions))

        if chunk:
            body.append("\n\n".join(chunk))

    if not body:
        return ""

    meta = [f"`{conv.get('source_tool') or 'unknown tool'}`"]
    if conv.get("model"):
        meta.append(f"Model `{conv['model']}`")
    if conv.get("git_branch"):
        meta.append(f"Branch `{conv['git_branch']}`")
    meta.append(f"{conv.get('message_count') or len(messages)} messages")

    header = [
        f"## {started.strftime('%Y-%m-%d %H:%M')} — {title}",
        "",
        " · ".join(meta),
        "",
        f"Session `{conv['session_id']}`" + (f" · Path `{_clean(project_path, redact)}`" if project_path else ""),
    ]
    if touched:
        links = ", ".join(link(p, project_path, redact=redact) for p in touched[:40])
        extra = f" *(+{len(touched) - 40} more)*" if len(touched) > 40 else ""
        header += ["", f"**Files changed:** {links}{extra}"]

    return "\n".join(header) + "\n\n" + "\n\n".join(body) + "\n"


# --------------------------------------------------------------------------- #
# Database                                                                    #
# --------------------------------------------------------------------------- #


def fetch_conversations(conn, *, include_generated: bool, project: str | None, since: str | None) -> list[dict]:
    where = ["TRUE"] if include_generated else ["c.generated_by IS NULL"]
    params: list[Any] = []
    if project:
        where.append("c.project_name = %s")
        params.append(project)
    if since:
        where.append("c.started_at >= %s")
        params.append(since)
    sql = f"""
        SELECT c.id, c.session_id, c.project_name, c.project_path, c.model,
               c.git_branch, c.started_at, c.ended_at, c.message_count,
               c.summary, c.source_tool
          FROM conversations c
         WHERE {" AND ".join(where)}
         ORDER BY c.project_name, c.started_at, c.id
    """
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(sql, params)
        return [dict(r) for r in cur.fetchall()]


def fetch_messages(conn, conversation_id: int) -> list[dict]:
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT role::text AS role, content, content_blocks, tool_calls, created_at
              FROM messages
             WHERE conversation_id = %s
             ORDER BY created_at, id
            """,
            (conversation_id,),
        )
        return [dict(r) for r in cur.fetchall()]


def fetch_memory(conn, project: str) -> list[dict]:
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT id, content, category::text AS category, tags, created_at
              FROM memory_chunks
             WHERE project_name = %s AND status = 'active'
             ORDER BY created_at, id
            """,
            (project,),
        )
        return [dict(r) for r in cur.fetchall()]


# --------------------------------------------------------------------------- #
# Writing                                                                     #
# --------------------------------------------------------------------------- #


def group_by_folder(conversations: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Bucket conversations by the folder they will be written to.

    Keyed by the folder name rather than the raw ``project_name``, because
    more than one name can sanitise to the same folder — ``project_name``
    is a generated column that yields ``unknown`` for a NULL path and an
    empty string for a path ending in a separator, and both become the
    folder ``unknown``. Keying by the raw name gives each a bucket, and
    the second one to be written silently overwrites the first.

    Each bucket comes back in chronological order, which merging two
    buckets would otherwise break.
    """
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for conv in conversations:
        grouped[safe_name(conv.get("project_name"))].append(conv)
    for bucket in grouped.values():
        bucket.sort(key=lambda c: (c["started_at"], c["id"]))
    return dict(grouped)


def write_parts(
    folder: Path,
    project: str,
    sections: list[tuple[datetime, str]],
    split_bytes: int,
    changed: set[Path] | None = None,
) -> list[Path]:
    """Write a project's sections, splitting into parts once they get large.

    A single file is the readable default. Splitting only kicks in when
    the whole project would land above ``split_bytes``, and each part
    then stays a contiguous stretch of time — sessions are never
    reordered, and a part is closed only when adding the next session
    would push it past the cap. Splitting on calendar months instead
    would be tidier to name and useless in practice: a month in which
    you worked every day still produces a file no editor wants to open.
    """
    total = sum(len(s.encode("utf-8")) for _, s in sections)

    def frontmatter(scope: str, count: int) -> str:
        # No run timestamp here on purpose. Stamping every project file with
        # the moment the export ran would change all of them on every run,
        # which defeats writing only what changed and makes each file's own
        # modification time meaningless. The run's date lives in README.md.
        return (
            "---\n"
            f'title: "{project}"\n'
            "tags: [throughline, export]\n"
            f'project: "{project}"\n'
            "---\n\n"
            f"# {project}\n\n"
            f"{count} sessions, oldest first{scope}.\n\n---\n\n"
        )

    written: list[Path] = []
    if total <= split_bytes or len(sections) < 2:
        path = folder / f"{safe_name(project)}.md"
        if (
            write_if_changed(path, frontmatter("", len(sections)) + "\n".join(s for _, s in sections))
            and changed is not None
        ):
            changed.add(path)
        return [path]

    parts: list[list[tuple[datetime, str]]] = [[]]
    size = 0
    for when, section in sections:
        weight = len(section.encode("utf-8"))
        if parts[-1] and size + weight > split_bytes:
            parts.append([])
            size = 0
        parts[-1].append((when, section))
        size += weight

    # Every part carries its index, not just the date it opens on. Naming
    # by date alone reads better but breaks the moment one busy day fills
    # two parts: they collide, and disambiguating only the repeats leaves
    # "Obsidian 2026-03-26 (03)" sorting ahead of "Obsidian 2026-03-26" in
    # every file listing. The index sorts the parts in the order they were
    # written, which is the order they should be read.
    for index, part in enumerate(parts, start=1):
        first, last = part[0][0], part[-1][0]
        span = f" · {first:%Y-%m-%d} to {last:%Y-%m-%d}"
        path = folder / f"{safe_name(project)} {index:02d} {first:%Y-%m-%d}.md"
        if write_if_changed(path, frontmatter(span, len(part)) + "\n".join(s for _, s in part)) and changed is not None:
            changed.add(path)
        written.append(path)
    return written


def write_memory(
    folder: Path, project: str, chunks: list[dict], *, redact: bool = False, changed: set[Path] | None = None
) -> Path | None:
    if not chunks:
        return None
    lines = [
        "---",
        f'title: "{project} — Memory"',
        "tags: [throughline, memory]",
        "---",
        "",
        f"# {project} — extracted memory\n",
        f"{len(chunks)} active entries, oldest first.\n",
    ]
    for chunk in chunks:
        when = chunk["created_at"].strftime("%Y-%m-%d %H:%M")
        tags = " ".join(f"#{t}" for t in (chunk.get("tags") or []) if t)
        lines.append(f"## {when} · {chunk['category']}\n")
        lines.append(prose(chunk["content"].strip(), redact))
        if tags:
            lines.append(f"\n{tags}")
        lines.append("")
    path = folder / "Memory.md"
    if write_if_changed(path, "\n".join(lines)) and changed is not None:
        changed.add(path)
    return path


def write_index(out: Path, stats: list[dict], failure: str | None = None, changed: set[Path] | None = None) -> Path:
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "---",
        'title: "Throughline"',
        "tags: [throughline, export]",
        f"exported: {stamp}",
        "---",
        "",
        "# Throughline",
        "",
        f"Throughline export taken on {stamp}. {len(stats)} projects, {sum(s['sessions'] for s in stats):,} sessions.",
        "",
        *(
            [
                f"> **This export is incomplete.** It stopped with: `{failure}`",
                ">",
                "> Everything listed below was written. Anything missing was never reached.",
                "",
            ]
            if failure
            else []
        ),
        "| Project | Sessions | From | To |",
        "| --- | ---: | --- | --- |",
    ]
    for row in sorted(stats, key=lambda s: s["last"], reverse=True):
        name = row["project"]
        lines.append(
            f"| [[{safe_name(name)}/{row['entry']}\\|{name}]] "
            f"| {row['sessions']} | {row['first']:%Y-%m-%d} | {row['last']:%Y-%m-%d} |"
        )
    path = out / "README.md"
    if write_if_changed(path, "\n".join(lines) + "\n") and changed is not None:
        changed.add(path)
    return path


# --------------------------------------------------------------------------- #
# Entry point                                                                 #
# --------------------------------------------------------------------------- #


# --------------------------------------------------------------------------- #
# The export                                                                  #
# --------------------------------------------------------------------------- #


#: Environment variable naming the directory the export may write inside.
#: Defaults to the user's home. The API needs a boundary because it has no
#: authentication: everything else it exposes is read-only, and an
#: unconstrained destination would turn it into a write-anywhere primitive.
_ROOT_ENV = "THROUGHLINE_EXPORT_ROOT"

#: Environment variable carrying the destination for a service-triggered run,
#: so a request body never has to reach the command line.
DEST_ENV = "THROUGHLINE_EXPORT_OUT"


def destination_from(argv_out: str | None) -> str:
    """The destination, from the command line or from the environment.

    A service-triggered run puts the path in ``THROUGHLINE_EXPORT_OUT``
    rather than on the command line, so the job registry keeps its
    guarantee that no request body ever becomes argv.
    """
    for candidate in (argv_out, os.environ.get(DEST_ENV)):
        if candidate and candidate.strip():
            return candidate.strip()
    raise ValueError(f"No destination given: neither --out nor {DEST_ENV}.")


def export_root() -> Path:
    """The directory the export is confined to."""
    configured = os.environ.get(_ROOT_ENV, "").strip()
    return Path(configured).expanduser().resolve() if configured else Path.home().resolve()


def resolve_destination(raw: str, *, root: Path | None = None) -> Path:
    """Validate a caller-supplied destination and return it resolved.

    Refuses anything that is not an absolute path inside *root*, and
    anything that names an existing file. Symlinks are resolved before the
    containment check, so a link inside the root pointing out of it does
    not get through.
    """
    boundary = (root or export_root()).expanduser().resolve()
    text = (raw or "").strip()
    if not text:
        raise ValueError("No destination given.")

    candidate = Path(text).expanduser()
    if not candidate.is_absolute():
        raise ValueError(f"The destination must be an absolute path: {text}")

    resolved = Path(os.path.normpath(candidate))
    # resolve() follows symlinks on the parts that exist, which is what the
    # containment check has to see; strict=False keeps a not-yet-created
    # destination legal.
    resolved = resolved.resolve()
    if resolved != boundary and boundary not in resolved.parents:
        raise ValueError(f"The destination is outside {boundary}: {resolved}")
    if resolved.is_file():
        raise ValueError(f"The destination is a file, not a directory: {resolved}")
    return resolved


def list_directory(raw: str | None, *, root: Path | None = None) -> dict[str, Any]:
    """List the immediate subdirectories of *raw* (or the export root).

    Backs an in-app folder browser rather than a native OS dialog: the API
    process may be running inside a Linux container with no display at all
    (Docker Compose's `web` service, for one), where nothing server-side can
    ever open the host's real file picker. Browsing the confined root itself
    needs no display and works identically in a container or a native
    install — the same containment rule as `resolve_destination`, except a
    browse target must already exist, where a destination need not.
    """
    boundary = (root or export_root()).expanduser().resolve()
    boundary.mkdir(parents=True, exist_ok=True)

    text = (raw or "").strip()
    target = Path(text).expanduser().resolve() if text else boundary
    if target != boundary and boundary not in target.parents:
        raise ValueError(f"The path is outside {boundary}: {target}")
    if not target.is_dir():
        raise ValueError(f"Not a directory: {target}")

    # Dotfiles/dirs are noise for choosing an export destination (`.git`,
    # `.throughline-export.json` from a previous run) and never useful here.
    dirs = sorted(
        (p for p in target.iterdir() if p.is_dir() and not p.name.startswith(".")),
        key=lambda p: p.name.lower(),
    )
    parent = target.parent if target != boundary else None
    return {
        "path": str(target),
        "root": str(boundary),
        "parent": str(parent) if parent is not None else None,
        "dirs": [{"name": p.name, "path": str(p)} for p in dirs],
    }


#: Record of what the last export wrote, kept in the destination itself.
#: Without it a re-run cannot tell its own stale output from the person's own
#: notes, and must either leave orphans behind or delete things it never made.
MANIFEST_NAME = ".throughline-export.json"


def read_manifest(out: Path) -> set[str]:
    """Relative paths the previous export wrote, or an empty set."""
    try:
        payload = json.loads((out / MANIFEST_NAME).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return set()
    files = payload.get("files")
    return {str(f) for f in files} if isinstance(files, list) else set()


def write_manifest(out: Path, paths: set[str]) -> None:
    (out / MANIFEST_NAME).write_text(
        json.dumps({"version": 1, "files": sorted(paths)}, ensure_ascii=False, indent=1),
        encoding="utf-8",
    )


def write_if_changed(path: Path, text: str) -> bool:
    """Write *text* to *path* only when it differs. Returns True if written.

    The destination is often a synced folder. Rewriting bytes that did not
    change makes the sync client re-upload the whole export and makes every
    file's timestamp useless as a record of when anything actually changed.
    """
    try:
        if path.read_text(encoding="utf-8") == text:
            return False
    except (OSError, ValueError):
        pass
    path.write_text(text, encoding="utf-8")
    return True


def prune(out: Path, previous: set[str], current: set[str]) -> int:
    """Delete files the last export wrote and this one did not.

    Only paths named in the previous manifest are eligible. Anything the
    person put in the destination themselves is untouched, whatever it is
    called and wherever it sits.
    """
    removed = 0
    for relative in sorted(previous - current):
        target = out / relative
        try:
            if target.is_file():
                target.unlink()
                removed += 1
        except OSError:
            continue
    # Clean up folders this export emptied, never one that still holds anything.
    for relative in sorted({str(Path(r).parent) for r in previous - current}, reverse=True):
        folder = out / relative
        if folder != out and folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()
    return removed


def export_corpus(
    out: Path | str,
    conversations: list[dict[str, Any]],
    load_messages: Callable[[int], list[dict[str, Any]]],
    load_memory: Callable[[str], list[dict[str, Any]]],
    *,
    tool_output: int = 0,
    split_bytes: int = DEFAULT_SPLIT_BYTES,
    redact: bool = False,
    memory: bool = True,
    on_project: Callable[[str, int, int], None] | None = None,
) -> dict[str, Any]:
    """Write *conversations* to *out* and report what was written.

    The two loaders are injected rather than reached for, so the same
    export runs behind the CLI, behind the API, and in a test with no
    database anywhere near it.
    """
    out = Path(out).expanduser()
    out.mkdir(parents=True, exist_ok=True)

    previous = read_manifest(out)
    produced: set[str] = set()
    changed: set[Path] = set()
    stats: list[dict[str, Any]] = []
    try:
        files = _write_projects(
            out,
            conversations,
            load_messages,
            load_memory,
            stats,
            produced,
            changed,
            tool_output=tool_output,
            split_bytes=split_bytes,
            redact=redact,
            memory=memory,
            on_project=on_project,
        )
    except Exception as exc:
        # A half-written export is not a disaster: the database is still the
        # archive, and re-running rewrites. A half-written export that *reads*
        # as a finished one is — so the index says what happened before the
        # failure propagates.
        write_index(out, stats, failure=f"{type(exc).__name__}: {exc}")
        # A failed run must not delete the previous run's files: what it did
        # not write this time it may simply never have reached.
        write_manifest(out, previous | produced)
        raise

    index = write_index(out, stats, changed=changed)
    produced.add(index.relative_to(out).as_posix())
    files += 1

    removed = prune(out, previous, produced)
    write_manifest(out, produced)

    return {
        "out": str(out),
        "projects": len(stats),
        "sessions": sum(s["sessions"] for s in stats),
        "files": files,
        "written": len(changed),
        "unchanged": files - len(changed),
        "removed": removed,
        "per_project": stats,
    }


def _write_projects(
    out: Path,
    conversations: list[dict[str, Any]],
    load_messages: Callable[[int], list[dict[str, Any]]],
    load_memory: Callable[[str], list[dict[str, Any]]],
    stats: list[dict[str, Any]],
    produced: set[str],
    changed: set[Path],
    *,
    tool_output: int,
    split_bytes: int,
    redact: bool,
    memory: bool,
    on_project: Callable[[str, int, int], None] | None,
) -> int:
    """Write every project folder, appending to *stats* as it goes.

    *stats* is passed in rather than returned so a caller that catches a
    failure still knows what got written before it.
    """
    files = 0
    for folder_name, convs in sorted(group_by_folder(conversations).items()):
        sections: list[tuple[datetime, str]] = []
        for conv in convs:
            rendered = render_session(conv, load_messages(conv["id"]), tool_output, redact=redact)
            if rendered:
                sections.append((conv["started_at"], rendered))
        if not sections:
            continue

        folder = out / folder_name
        folder.mkdir(parents=True, exist_ok=True)
        written = write_parts(folder, folder_name, sections, split_bytes, changed)
        produced.update(p.relative_to(out).as_posix() for p in written)
        files += len(written)

        if memory:
            # One folder can hold more than one project_name; collect the
            # memory filed under each of them, oldest first.
            chunks: list[dict[str, Any]] = []
            for name in dict.fromkeys(c.get("project_name") or "" for c in convs):
                chunks.extend(load_memory(name))
            # created_at alone leaves ties to the database's whim, and a
            # differently-ordered Memory.md reads as a change that is not one.
            chunks.sort(key=lambda c: (c["created_at"], c.get("id") or 0))
            memory_file = write_memory(folder, folder_name, chunks, redact=redact, changed=changed)
            if memory_file:
                produced.add(memory_file.relative_to(out).as_posix())
                files += 1

        stats.append(
            {
                "project": folder_name,
                "entry": written[0].stem,
                "sessions": len(sections),
                "files": len(written),
                "first": sections[0][0],
                "last": sections[-1][0],
            }
        )
        if on_project:
            on_project(folder_name, len(sections), len(written))

    return files


def build_parser() -> argparse.ArgumentParser:
    """The command-line surface, separate from running it."""
    parser = argparse.ArgumentParser(
        prog="throughline export-markdown",
        description="Export the stored corpus as a Markdown vault, one folder per project.",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Destination directory (created if missing). Falls back to $THROUGHLINE_EXPORT_OUT.",
    )
    parser.add_argument("--project", default=None, help="Export a single project instead of all.")
    parser.add_argument("--since", default=None, help="Only sessions started on or after this date (YYYY-MM-DD).")
    parser.add_argument(
        "--include-generated",
        action="store_true",
        help="Also export machine-generated conversations (default: human sessions only).",
    )
    parser.add_argument(
        "--tool-output",
        type=int,
        default=0,
        help="Characters of each tool result to include, in a collapsed block (default: 0, omit them).",
    )
    parser.add_argument(
        "--split-bytes",
        type=int,
        default=DEFAULT_SPLIT_BYTES,
        help=f"Split a project into monthly files above this size (default: {DEFAULT_SPLIT_BYTES}).",
    )
    parser.add_argument("--no-memory", action="store_true", help="Skip the per-project Memory.md file.")
    parser.add_argument(
        "--redact",
        action="store_true",
        help="Run every exported text through the PII pass (keys, tokens, emails, home paths).",
    )
    return parser


#: Options a service-triggered run passes through the environment, so the
#: fixed job command line never has to carry a caller's values.
_ENV_OPTIONS = {
    "project": "THROUGHLINE_EXPORT_PROJECT",
    "since": "THROUGHLINE_EXPORT_SINCE",
    "include_generated": "THROUGHLINE_EXPORT_INCLUDE_GENERATED",
    "redact": "THROUGHLINE_EXPORT_REDACT",
    "tool_output": "THROUGHLINE_EXPORT_TOOL_OUTPUT",
    "no_memory": "THROUGHLINE_EXPORT_NO_MEMORY",
}


def _env_flag(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in {"1", "true", "yes", "on"}


def options_from(args: argparse.Namespace) -> dict[str, Any]:
    """Resolve every option from the command line, then the environment.

    An explicit flag always wins. A malformed environment value is ignored
    rather than fatal: the run that matters is the one the person asked
    for, and refusing it over an unparseable number nobody typed would be
    the wrong trade.
    """
    try:
        env_tool_output = int(os.environ.get(_ENV_OPTIONS["tool_output"], "") or 0)
    except ValueError:
        env_tool_output = 0

    return {
        "out": destination_from(args.out),
        "project": args.project or (os.environ.get(_ENV_OPTIONS["project"], "").strip() or None),
        "since": args.since or (os.environ.get(_ENV_OPTIONS["since"], "").strip() or None),
        "include_generated": args.include_generated or _env_flag(_ENV_OPTIONS["include_generated"]),
        "redact": args.redact or _env_flag(_ENV_OPTIONS["redact"]),
        "tool_output": args.tool_output or env_tool_output,
        "split_bytes": args.split_bytes,
        "memory": not (args.no_memory or _env_flag(_ENV_OPTIONS["no_memory"])),
    }


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    try:
        opts = options_from(args)
        out = Path(opts["out"]).expanduser()
        out.mkdir(parents=True, exist_ok=True)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"ERROR: cannot create {opts['out']}: {exc}", file=sys.stderr)
        return 2

    try:
        conn = psycopg2.connect(**db_config())
    except psycopg2.Error as exc:
        print(f"ERROR: database unreachable: {exc}", file=sys.stderr)
        return 1

    try:
        conversations = fetch_conversations(
            conn,
            include_generated=opts["include_generated"],
            project=opts["project"],
            since=opts["since"],
        )
        if not conversations:
            print("Nothing to export for the given filters.", file=sys.stderr)
            return 0

        summary = export_corpus(
            out,
            conversations,
            lambda cid: fetch_messages(conn, cid),
            lambda name: fetch_memory(conn, name),
            tool_output=opts["tool_output"],
            split_bytes=opts["split_bytes"],
            redact=opts["redact"],
            memory=opts["memory"],
            on_project=lambda name, sessions, files: print(f"{name}: {sessions} sessions -> {files} file(s)"),
        )
        print(
            f"\n{summary['projects']} projects, {summary['files']} files in {summary['out']}\n"
            f"{summary['written']} written, {summary['unchanged']} unchanged, {summary['removed']} removed"
        )
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
