"""Spawn ~/ai-pipeline/pipeline.sh for a resolved team.

Security note (see Global Constraints in the implementation plan): every
value that reaches the subprocess arrives through `subprocess.Popen`'s
`args` list and `env` dict, never through a shell string. The task
description the user typed is exactly one argv element — Popen with
shell=False (the default) passes it to the OS as one argument regardless of
any quote or `;` characters it contains, so there is no path from a
request body to an injected shell command, matching the same principle
throughline/api/jobs.py already states for its own fixed job registry.

Windows note: pipeline.sh is a bash script and Popen cannot exec a .sh file
via shebang on Windows (there is no kernel-level shebang interpretation
outside a POSIX exec). We always spawn it as `bash <script> ...` — bash is
present on every platform we target (Git Bash on Windows, native bash on
Linux/macOS) — rather than relying on the OS to dispatch by extension.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import uuid
from pathlib import Path
from typing import Any

import psutil

from throughline.queries import pm as Q

PIPELINE_SCRIPT = Path(
    os.environ.get("AI_PIPELINE_SCRIPT_PATH", str(Path.home() / "ai-pipeline" / "pipeline.sh"))
)

# Resolved once at import time via PATH search rather than passed to Popen
# as the bare literal "bash". On Windows, CreateProcess (which Popen calls
# for an extension-less executable name) searches System32 *before*
# consulting PATH — and Windows 11 ships a WSL-relay shim at
# C:\Windows\System32\bash.exe that intercepts a bare "bash" and fails with
# "execvpe(/bin/bash) failed: No such file or directory" instead of running
# Git Bash, even when Git's own bash.exe appears earlier in PATH. Resolving
# the absolute path via shutil.which (a plain PATH scan, no System32
# priority) sidesteps that and always lands on the intended bash — Git Bash
# on Windows, the system bash elsewhere. Falls back to the literal "bash"
# if none is found on PATH so the failure mode is a normal
# FileNotFoundError from Popen rather than a silent None.
BASH_EXECUTABLE = shutil.which("bash") or "bash"

_STEP_TO_CONTEXT_VAR = {
    "analyst": "AI_PIPELINE_ANALYST_CONTEXT",
    "executor": "AI_PIPELINE_EXECUTOR_CONTEXT",
    "tester": "AI_PIPELINE_TESTER_CONTEXT",
}


def ensure_vibe_agent_profile(resolved: dict[str, Any], profile_name: str) -> Path:
    """Write ~/.vibe/agents/<profile_name>.toml so a role/member's resolved
    AI binding is usable as a --agent for `vibe -p`. Always overwrites
    (never goes stale, no separate "is this profile up to date" check
    needed) and always read-only (write_file/edit = never) — this generator
    is only ever used for the Tester role's binding; an Executor bound to
    Vibe instead of Aider is out of scope for this iteration (spec §2 lists
    only the three-role pattern already proven on 2026-08-25).

    Mirrors ~/.vibe/agents/tester-local.toml, hand-written and verified
    working against a live `vibe -p` call earlier in this project.
    """
    agents_dir = Path.home() / ".vibe" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    path = agents_dir / f"{profile_name}.toml"

    instructions = resolved.get("instructions") or ""
    lines = [
        f'display_name = "{profile_name}"',
        f'description = "Auto-generated by Throughline PM for {profile_name} — read-only, local model"',
        'safety = "safe"',
        "",
        'disabled_tools = ["exit_plan_mode"]',
        "",
        "[tools.write_file]",
        'permission = "never"',
        "",
        "[tools.edit]",
        'permission = "never"',
        "",
        f'active_model = "{profile_name}-model"',
        f'allowed_models = ["{profile_name}-model"]',
        "",
        "[[providers]]",
        f'name = "{profile_name}-provider"',
        'api_base = "http://127.0.0.1:11434/v1"',
        'backend = "generic"',
        "",
        "[[models]]",
        f'name = "{resolved["ai_model"]}"',
        f'provider = "{profile_name}-provider"',
        f'alias = "{profile_name}-model"',
        "temperature = 0.2",
    ]
    if instructions:
        # TOML `#` comments end at end-of-line — resolve_assignment joins
        # role+member instructions with "\n\n", so a single `# ...` line
        # embedding the raw (possibly multi-line) text would let everything
        # after the first newline fall through as bare top-level TOML,
        # potentially ahead of the [tools.write_file]/[tools.edit]
        # permission="never" blocks this file exists to enforce. Every
        # physical line of the instructions must get its own `#` prefix.
        comment_lines = [f"# {line}" for line in instructions.splitlines()]
        lines[3:3] = ["# Role/member instructions:", *comment_lines]

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _write_context_file(tmp_dir: Path, step: str, resolved: dict[str, Any]) -> Path | None:
    lines = []
    if resolved["instructions"]:
        lines.append(resolved["instructions"])
    if resolved["skill_refs"]:
        lines.append("Verwende diese Skills: " + ", ".join(str(s) for s in resolved["skill_refs"]))
    if resolved["document_refs"]:
        lines.append("Relevante Dokumente: " + ", ".join(resolved["document_refs"]))
    if not lines:
        return None
    path = tmp_dir / f"{step}-context.md"
    path.write_text("\n\n".join(lines), encoding="utf-8")
    return path


def launch_task(
    conn, *, pm_project_id: int, team_id: int, title: str, repo_path: str
) -> dict[str, Any]:
    teams = Q.get_project_teams(conn, pm_project_id)
    team = next((t for t in teams if t["id"] == team_id), None)
    if team is None:
        raise ValueError(f"Team {team_id} is not linked to project {pm_project_id}")

    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT a.id, r.name AS role_name FROM pm_assignments a
            JOIN pm_roles r ON r.id = a.role_id
            WHERE a.pm_project_id = %s AND a.team_id = %s
            """,
            (pm_project_id, team_id),
        )
        assignment_rows = cur.fetchall()

    # NOTE (controller ruling, overrides an earlier draft): a run_id derived
    # from pm_project_id/team_id/os.getpid()/len(assignment_rows) collides
    # across repeated launches of the same team, and pm_tasks has a
    # UNIQUE (repo_path, run_id) index — so use a random suffix instead.
    run_id = f"pm-{pm_project_id}-{team_id}-{uuid.uuid4().hex[:8]}"

    # Context files live inside the run's own log directory rather than a
    # tempfile.mkdtemp() dir — a temp dir is never cleaned up here (one
    # leaked directory per launch, unbounded), whereas
    # <repo_path>/.ai-pipeline/<run_id>/ already lives with the rest of the
    # run's artifacts, gets cleaned up along with the repo, and doubles as
    # an audit trail of exactly what each role was told.
    log_dir = Path(repo_path) / ".ai-pipeline" / run_id
    ctx_dir = log_dir / "context"
    ctx_dir.mkdir(parents=True, exist_ok=True)

    env = dict(os.environ)
    env["AI_PIPELINE_RUN_ID"] = run_id
    # pipeline.sh's child tools (vibe in particular) crash with
    # UnicodeEncodeError under codepage 850 when stdout is redirected on
    # Windows — force UTF-8 I/O for the whole subprocess tree.
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"

    role_to_env_model = {"executor": "AI_PIPELINE_EXECUTOR_MODEL", "tester": "AI_PIPELINE_TESTER_AGENT"}

    for assignment_id, role_name in assignment_rows:
        resolved = Q.resolve_assignment(conn, assignment_id)
        role_key = role_name.strip().lower()

        ctx_var = _STEP_TO_CONTEXT_VAR.get(role_key)
        if ctx_var:
            ctx_file = _write_context_file(ctx_dir, role_key, resolved)
            if ctx_file:
                env[ctx_var] = str(ctx_file)

        model_var = role_to_env_model.get(role_key)
        if model_var and resolved["ai_model"]:
            if role_key == "tester" and resolved["ai_tool"] == "vibe":
                profile_name = f"pm-{assignment_id}"
                ensure_vibe_agent_profile(resolved, profile_name)
                env[model_var] = profile_name
            else:
                env[model_var] = resolved["ai_model"]

    # Windows note (controller ruling): Popen cannot exec a .sh file via
    # shebang, so pipeline.sh is always invoked through bash explicitly —
    # this matches how the fake test script is invoked too.
    process = subprocess.Popen(
        [BASH_EXECUTABLE, str(PIPELINE_SCRIPT), title, repo_path, "300"],
        env=env,
        cwd=repo_path,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        shell=False,
    )

    task = Q.create_task(
        conn, pm_project_id=pm_project_id, team_id=team_id, title=title,
        run_id=run_id, repo_path=repo_path, log_dir=str(log_dir), pid=process.pid,
    )
    Q.set_task_status(conn, task["id"], "running")
    return Q.get_task(conn, task["id"])


def stop_task(conn, task_id: int) -> dict[str, Any]:
    """Kill the whole process tree, not just the recorded PID.

    pipeline.sh runs under Git Bash on Windows and spawns aider/vibe/claude
    as children that are not reliably reachable through a POSIX process
    group the way they would be on Linux/macOS — psutil's recursive
    `children()` walk is the portable way to find them regardless. On
    Windows, psutil's terminate() is a hard TerminateProcess (there is no
    graceful SIGTERM equivalent), so the terminate-then-kill escalation
    below still runs, it just has less room to matter there than on
    POSIX — the wait_procs timeouts are what give a well-behaved POSIX
    child a chance to exit cleanly before the kill() escalation.
    """
    task = Q.get_task(conn, task_id)
    pid = task["pid"]
    if pid is not None:
        try:
            parent = psutil.Process(pid)
            children = parent.children(recursive=True)
            for child in children:
                try:
                    child.terminate()
                except psutil.NoSuchProcess:
                    pass
            _, alive = psutil.wait_procs(children, timeout=3)
            for child in alive:
                child.kill()
            parent.terminate()
            parent.wait(timeout=3)
        except psutil.NoSuchProcess:
            pass  # already gone — stopping an already-dead process is not an error
        except psutil.TimeoutExpired:
            try:
                parent.kill()
            except psutil.NoSuchProcess:
                pass

    Q.set_task_status(conn, task_id, "stopped")
    return Q.get_task(conn, task_id)
