import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {MemoryRouter} from "react-router-dom";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {it,expect,vi} from "vitest";
import {AiSettings} from "./AiSettings";
const mocks=vi.hoisted(()=>({request:vi.fn(),providers:vi.fn(),models:vi.fn()}));
vi.mock("@/lib/api",()=>({request:mocks.request,pmApi:{listAiProviders:mocks.providers,refreshAiProviderModels:mocks.models}}));
it("saves an explicit local embedding model and never offers a chat CLI for embeddings",async()=>{
 mocks.request.mockImplementation(async()=>({purposes:["embeddings"],bindings:[],bridge:{clis:{codex:{installed:true}}}}));
 mocks.providers.mockResolvedValue({providers:[{id:1,name:"Local AI",provider_type:"ollama",base_url:"http://localhost:11434",custom_models:[],enabled:true}]});
 mocks.models.mockResolvedValue({models:["nomic-embed-text"],unavailable:false});
 render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter><AiSettings/></MemoryRouter></QueryClientProvider>);
 const provider=await screen.findByRole("combobox",{name:"Provider or installed CLI"});
 await screen.findByRole("option",{name:"Local AI · ollama"});
 expect(screen.queryByRole("option",{name:/codex/})).toBeNull();
 await userEvent.selectOptions(provider,"api:1");
 await userEvent.type(screen.getByRole("combobox",{name:"Model"}),"nomic-embed-text");
 await userEvent.click(screen.getByRole("button",{name:"Save"}));
 await waitFor(()=>expect(mocks.request.mock.calls.some(call=>call[0]==="/ai/settings/embeddings"&&call[1]?.method==="PUT")).toBe(true));
 const saved=mocks.request.mock.calls.find(call=>call[1]?.method==="PUT")!;
 expect(JSON.parse(saved[1].body)).toEqual({provider_id:1,cli:null,model:"nomic-embed-text",embedding_dim:768});
});
