#!/usr/bin/env python3
"""
Context Pre-Loader für Claude Code SessionStart-Hook.

Schreibt relevante Memory-Chunks als Markdown nach
    $CLAUDE_PROJECT_DIR/.claude/MEMORY_CONTEXT.md
(oder $PWD/.claude/MEMORY_CONTEXT.md falls env var fehlt).

Claude Code liest diese Datei beim Session-Start automatisch als Zusatz-Context.

Scoring:
  - Filter 1: project_name ILIKE %project%       (gleicher Projekt-Name)
  - Filter 2: category IN (decision, preference, pattern, error_solution, project_context)
  - Sortierung: confidence DESC, created_at DESC
  - Top 20

Exit 0 immer (Hook darf Session nicht blockieren).
"""

from __future__ import annotations

import os
import sys
import traceback
from datetime import datetime
from pathlib import Path

import psycopg2
import psycopg2.extras

DB_CONFIG = {
    "dbname": os.environ.get("PGDATABASE", "claude_memory"),
    "user": os.environ.get("PGUSER", os.environ.get("USER", "postgres")),
    "host": os.environ.get("PGHOST", "localhost"),
    "port": int(os.environ.get("PGPORT", "5432")),
}

# Kategorien die ins CLAUDE.md-Injection gehören
RELEVANT_CATEGORIES = ("decision", "preference", "pattern", "error_solution", "project_context")
TOP_N = 20

CATEGORY_LABELS = {
    "decision": "Decisions",
    "preference": "Preferences",
    "pattern": "Patterns",
    "error_solution": "Known Error Solutions",
    "project_context": "Project Context",
    "contact": "Known Contacts",
    "insight": "Insights",
    "workflow": "Workflows",
}

CATEGORY_ORDER = [
    "project_context",
    "decision",
    "preference",
    "pattern",
    "error_solution",
    "contact",
    "insight",
    "workflow",
]


def get_project_dir() -> Path:
    pd = os.environ.get("CLAUDE_PROJECT_DIR") or os.environ.get("PWD") or os.getcwd()
    return Path(pd).resolve()


def get_project_name(project_dir: Path) -> str:
    return project_dir.name


def fetch_relevant(cursor, project_name: str) -> list:
    """
    Holt primär Chunks mit passendem project_name, fällt zurück auf globale Chunks.
    """
    like = f"%{project_name}%"
    cursor.execute(f"""
        WITH by_project AS (
            SELECT id, content, category::text AS category, tags, confidence, project_name, created_at,
                   1 AS priority
            FROM memory_chunks
            WHERE project_name ILIKE %s
              AND category IN %s
        ),
        by_category AS (
            SELECT id, content, category::text AS category, tags, confidence, project_name, created_at,
                   2 AS priority
            FROM memory_chunks
            WHERE (project_name IS NULL OR project_name NOT ILIKE %s)
              AND category IN %s
        )
        SELECT * FROM (
            SELECT * FROM by_project
            UNION ALL
            SELECT * FROM by_category
        ) x
        ORDER BY priority ASC, confidence DESC NULLS LAST, created_at DESC
        LIMIT %s
    """, (like, RELEVANT_CATEGORIES, like, RELEVANT_CATEGORIES, TOP_N))
    return cursor.fetchall()


def fetch_contacts(cursor, project_name: str, limit: int = 10) -> list:
    like = f"%{project_name}%"
    cursor.execute("""
        SELECT id, content, category::text AS category, tags, confidence, project_name, created_at
        FROM memory_chunks
        WHERE category = 'contact'
          AND (project_name ILIKE %s OR project_name IS NULL)
        ORDER BY confidence DESC NULLS LAST, created_at DESC
        LIMIT %s
    """, (like, limit))
    return cursor.fetchall()


def format_chunk(r) -> str:
    cat = r.get("category") or "note"
    conf = r.get("confidence")
    content = (r.get("content") or "").strip().replace("\r", "")
    conf_str = ""
    try:
        if conf is not None:
            conf_str = f", {float(conf):.2f}"
    except Exception:
        pass
    tags = r.get("tags") or []
    tag_str = ""
    if tags:
        tag_str = " _(tags: " + ", ".join(tags[:5]) + ")_"
    # Leading dash, inline content. If content has newlines, indent them.
    if "\n" in content:
        first, *rest = content.split("\n")
        rest_indent = "\n  ".join(r.rstrip() for r in rest if r.strip())
        body = first + ("\n  " + rest_indent if rest_indent else "")
    else:
        body = content
    return f"- [{cat}{conf_str}] {body}{tag_str}"


def render_markdown(project_name: str, project_dir: Path, chunks: list, contacts: list) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = []
    lines.append("<!-- Auto-generated by context_preload.py — do not edit -->")
    lines.append(f"# Relevant Memory from Past Sessions")
    lines.append("")
    lines.append(f"_Loaded {now} for project **{project_name}** (`{project_dir}`)._")
    lines.append("")
    lines.append(
        "This file is auto-injected by the `SessionStart` hook from the "
        "`claude_memory` PostgreSQL DB. It surfaces prior decisions, preferences, "
        "patterns and known issues. Treat it as trusted long-term context."
    )
    lines.append("")

    if not chunks and not contacts:
        lines.append("_No relevant memory found yet. As you work, extracted chunks will appear here._")
        return "\n".join(lines) + "\n"

    # Gruppieren
    by_cat: dict[str, list] = {}
    for r in chunks:
        by_cat.setdefault(r["category"], []).append(r)
    for r in contacts:
        by_cat.setdefault("contact", []).append(r)

    for cat in CATEGORY_ORDER:
        if cat not in by_cat:
            continue
        label = CATEGORY_LABELS.get(cat, cat.title())
        lines.append(f"## {label}")
        for r in by_cat[cat]:
            lines.append(format_chunk(r))
        lines.append("")

    # Rest (unbekannte Kategorien)
    for cat, rows in by_cat.items():
        if cat in CATEGORY_ORDER:
            continue
        lines.append(f"## {CATEGORY_LABELS.get(cat, cat.title())}")
        for r in rows:
            lines.append(format_chunk(r))
        lines.append("")

    return "\n".join(lines) + "\n"


def write_output(project_dir: Path, content: str) -> Path:
    out_dir = project_dir / ".claude"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "MEMORY_CONTEXT.md"
    out_file.write_text(content, encoding="utf-8")
    return out_file


def main() -> int:
    project_dir = get_project_dir()
    project_name = get_project_name(project_dir)

    try:
        conn = psycopg2.connect(connect_timeout=3, **DB_CONFIG)
    except Exception as e:
        # DB nicht erreichbar — still + leise, Hook darf nicht blockieren.
        try:
            write_output(project_dir, (
                f"<!-- Memory DB not reachable: {type(e).__name__} -->\n"
                f"# Relevant Memory from Past Sessions\n\n"
                f"_DB unreachable — no memory context loaded._\n"
            ))
        except Exception:
            pass
        print(f"[context_preload] DB nicht erreichbar: {e}", file=sys.stderr)
        return 0

    try:
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        chunks = fetch_relevant(cur, project_name)
        contacts = fetch_contacts(cur, project_name)
        md = render_markdown(project_name, project_dir, chunks, contacts)
        out_file = write_output(project_dir, md)
        print(f"[context_preload] wrote {out_file} ({len(chunks)} chunks, {len(contacts)} contacts) for project='{project_name}'")
    except Exception as e:
        print(f"[context_preload] Fehler: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
    finally:
        try:
            conn.close()
        except Exception:
            pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
