#!/usr/bin/env bash
# Install (or refresh) the automatic nightly backup agent.
#
# Why this exists rather than pointing launchd straight at scripts/backup.sh:
# on modern macOS, ~/Documents, ~/Desktop and ~/Downloads are TCC-protected.
# A launchd agent has no Full Disk Access, so executing a script that lives in
# a checkout under ~/Documents fails with:
#
#     /bin/bash: .../scripts/backup.sh: Operation not permitted
#
# launchd records exit status 32256 and the backup silently never runs — the
# worst failure mode for a backup, because nothing tells you.
#
# So the runnable copy is installed to ~/.local/bin, which is not protected.
# Re-run this script after editing scripts/backup.sh to refresh that copy.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_DIR/scripts/backup.sh"
BIN_DIR="$HOME/.local/bin"
DEST="$BIN_DIR/throughline-backup.sh"
LABEL="com.claude-memory-backup"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_DIR="$HOME/Library/Logs"

[ -f "$SRC" ] || { echo "ERROR: $SRC not found" >&2; exit 1; }

mkdir -p "$BIN_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"

# Stamp the copy so its provenance is obvious to anyone who finds it later.
{
    echo "#!/usr/bin/env bash"
    echo "# INSTALLED COPY — generated by scripts/install_backup_agent.sh"
    echo "# Source: $SRC"
    echo "# Installed: $(date)"
    echo "# Do not edit here; edit the source and re-run the installer."
    tail -n +2 "$SRC"
} > "$DEST"
chmod +x "$DEST"
echo "Installed runnable copy: $DEST"

PG_BIN_DIR="${PG_BIN:-/opt/homebrew/opt/postgresql@16/bin}"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$DEST</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>$PG_BIN_DIR:/opt/homebrew/bin:/usr/bin:/bin</string>
        <key>PG_BIN</key>
        <string>$PG_BIN_DIR</string>
        <key>PGUSER</key>
        <string>${PGUSER:-$USER}</string>
        <key>PGDATABASE</key>
        <string>${PGDATABASE:-throughline}</string>
        <key>PGHOST</key>
        <string>${PGHOST:-localhost}</string>
        <key>PGPORT</key>
        <string>${PGPORT:-5432}</string>
    </dict>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>3</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/claude-memory-backup.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/claude-memory-backup.err</string>
</dict>
</plist>
PLIST_EOF

plutil -lint "$PLIST" >/dev/null
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

echo "Loaded agent:   $LABEL (daily 03:00)"
echo "Logs:           $LOG_DIR/claude-memory-backup.{log,err}"
echo "Backups:        ${CLAUDE_MEMORY_BACKUP_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/claude-memory/backups}"
echo
echo "Run now:        launchctl start $LABEL"
echo "Remove:         launchctl unload $PLIST && rm $PLIST $DEST"
